version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Greeting
          command: docker run -it --rm alpine echo hoge
      - run:
          name: Print the Current Time
          command: date
